config/routes.rb
WixGallery::Application.routes.draw do
  resources :users, :only => [:index] do
    resources :photos, :only => [:create,:update,:destroy,:index] do
      collection do
        get :preview
      end
    end
  end
  root :to => 'users#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  
  validates :title, :presence => true
  validates :preview_url, :presence => true
  validates :url, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :html, :js
  before_filter Proc.new { @user = User.find params[:user_id] }
  before_filter Proc.new { @photos = @user.photos.all }, :only => [:index, :preview]
  
  def index; end
  
  def preview; end
  
  def create
    @photo = @user.photos.create params[:photo]
  end
  
  def update
    @photo = @user.photos.find params[:id]
    @photo.update_attributes params[:photo]
  end
  
  def destroy
    @photo = @user.photos.find params[:id]
    @photo.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WixGallery</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_photo.html.erb
<li id="photo_<%= (!photo.new_record?) ? photo.id : 'new' -%>">
  <%= form_for photo, :url => (!photo.new_record?) ? user_photo_path(photo.user_id, photo) : user_photos_path(@user), :remote => true do |f|%>
    <fieldset>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </fieldset>
    <fieldset>
      <%= f.label :preview_url %>
      <%= f.text_field :preview_url %>
    </fieldset>
    <fieldset>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </fieldset>
    <fieldset class="controls">
    <%= submit_tag 'Save' %>
    <% if !photo.new_record? %> or <%= link_to 'Delete', user_photo_path(photo.user_id, photo), :remote => true, :method => :delete, :confirm => 'Sure about that?'  %><% end %>
    </fieldset>
  <% end %>
</li>

app/views/photos/create.js.erb
<% if @photo.valid? %>
$('#photos_container').append("<%= escape_javascript(render(:partial => @photo)) -%>");
$('#photo_<%= @photo.id %>').effect("highlight", {}, 3000);
$('#photo_new').replaceWith("<%= escape_javascript(render(:partial => Photo.new)) -%>");
<% else %>
$('#photo_new').replaceWith("<%= escape_javascript(render(:partial => @photo)) -%>");
<% end %>

app/views/photos/destroy.js.erb
$('#photo_<%= @photo.id -%>').hide('clip',{},600, function(){$(this).remove()});

app/views/photos/index.html.erb
<h3>Edit</h3>
<%= link_to 'home', root_path %> | <%= link_to 'preview', preview_user_photos_path(@user) %>
<ul class="list">
  <span id="photos_container">
  <%= render :partial => 'photo', :collection => @photos %>
  </span>
  <%= render :partial => 'photo',  :locals => { :photo => Photo.new } %>
</ul>

app/views/photos/preview.html.erb
<h3>Preview</h3>
<%= link_to 'home', root_path %> | <%= link_to 'edit', user_photos_path(@user) %>
<ul class="matrix">
  <% @photos.each do |photo|%>
  <li><%= link_to image_tag(photo.preview_url, :alt => photo.title, :title => photo.title), photo.url %></li>
  <% end %>
</ul>

app/views/photos/update.js.erb
$('#photo_<%= @photo.id %>').replaceWith("<%= escape_javascript(render(:partial => @photo)) -%>");
<% if @photo.valid? %>
$('#photo_<%= @photo.id %>').effect("highlight", {}, 3000);
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="list">
  <% @users.each do |u|%>
    <li class="padded"><%= link_to "edit photos for user ##{u.id}", user_photos_path(u) %></li>
  <% end %>
</ul>